<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="bartrover">

    <!-- ********************** INERTIA MACROS *********************************  -->
    <xacro:include filename="inertial_macros.xacro" />
    <!-- ********************** MATERIAL MACROS *********************************  -->
    <xacro:include filename="material_macros.xacro" />
    <!-- ********************** CONSTANTS MACROS *********************************  -->
    <xacro:include filename="constants_macros.xacro" />


	<!-- ********************** BASE LINK *********************************  -->
    <link name="base_link">
    </link>
    <gazebo reference="base_link">
        <material>Gazebo/White</material>
    </gazebo>
	
    <!-- ********************** BODY LINK *********************************  -->
    <joint name="base_joint" type="fixed">
        <axis rpy="0 0 0" xyz="0 0 0"/>
        <parent link="base_link" />
        <child link="body_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>
    
    <link name="body_link">
		<visual>
			<origin xyz="0 0 0.03" rpy="0 0 0" />
            <geometry>
                <box size="0.28 ${wheel_separation} 0.08"/>
            </geometry>
			<material name="White" />
		</visual>
		<collision>
			<origin xyz="0 0 0.03" rpy="0 0 0" />
            <geometry>
                <box size="0.28 ${wheel_separation} 0.08"/>
            </geometry>
		</collision>
        <inertial>
            <origin xyz="0 0 0.03" rpy="0 0 0" />
            <mass value="${mass}" />
            <inertia ixx="${inertia}" ixy="0.0" ixz="0.0" iyy="${inertia}" iyz="0.0" izz="${inertia}" />
        </inertial>
	</link>
    <gazebo reference="body_link">
        <material>Gazebo/White</material>
    </gazebo>


    <!-- ********************** WHEEL LINKS REAR ********************************* -->
    <!-- ********************** LEFT ********************************* -->
    <joint name="rear_left_wheel_joint" type="continuous">
        <parent link="body_link" />
        <child link="rear_left_wheel" />
        <origin xyz="-0.104 ${wheel_separation/2 + wheel_width/2} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>
    
    <link name="rear_left_wheel">
        <visual>
			<origin xyz="0 0 0" rpy="${PI / 2} 0 0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="Red" />
        </visual>
        <collision>
			<origin xyz="0 0 0" rpy="${PI / 2} 0 0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_width}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="rear_left_wheel">
        <mu1 value="${lateral_friction}" />
        <mu2 value="${spinning_friction}" />
        <kp value="${contact_stiffness}" />
        <kd value="${contact_damping}" />
        <fdir1 value="1 0 0"/>
        <minDepth>0</minDepth>
        <material>Gazebo/Red</material>
    </gazebo>

    <joint name="rear_left_marker_joint" type="fixed">
        <parent link="rear_left_wheel" />
        <child link="rear_left_marker" />
        <origin xyz="0.015 0.0175 0" rpy="0 0 0" />
    </joint>

    <link name="rear_left_marker">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.03 0.005 0.005" />
            </geometry>
            <material name="White" />
        </visual>
        <inertial>
            <mass value="${marker_mass}" />
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
        </inertial>
    </link>
    <gazebo reference="rear_left_marker">
        <material>Gazebo/White</material>
    </gazebo>

    <!-- ********************** RIGHT ********************************* -->
    <joint name="rear_right_wheel_joint" type="continuous">
        <parent link="body_link" />
        <child link="rear_right_wheel" />
		<origin xyz="-0.104 ${-1 * (wheel_separation/2 + wheel_width/2)} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="rear_right_wheel">
        <visual>
			<origin xyz="0 0 0" rpy="${PI / 2} 0 0" />
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
            </geometry>
            <material name="Red" />
        </visual>
        <collision>
			<origin xyz="0 0 0" rpy="${PI / 2} 0 0" />
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_width}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="rear_right_wheel">
        <mu1 value="${lateral_friction}" />
        <mu2 value="${spinning_friction}" />
        <kp value="${contact_stiffness}" />
        <kd value="${contact_damping}" />
        <fdir1 value="1 0 0"/>
        <minDepth>0</minDepth>
        <material>Gazebo/Red</material>
    </gazebo>

    <joint name="rear_right_marker_joint" type="fixed">
        <parent link="rear_right_wheel" />
        <child link="rear_right_marker" />
        <origin xyz="0.015 -0.0175 0" rpy="0 0 0" />
    </joint>

    <link name="rear_right_marker">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.03 0.005 0.005" />
            </geometry>
            <material name="White" />
        </visual>
        <inertial>
            <mass value="${marker_mass}" />
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
        </inertial>
    </link>
    <gazebo reference="rear_right_marker">
        <material>Gazebo/White</material>
    </gazebo>

    
    <!-- ********************** WHEEL LINKS MIDDLE ********************************* --> 
    <!-- ********************** LEFT ********************************* -->
    <joint name="middle_left_wheel_joint" type="continuous">
        <parent link="body_link" />
        <child link="middle_left_wheel" />
		<origin xyz="0 ${wheel_separation/2 + wheel_width/2} 0" rpy="0 0 0" />
        <axis xyz="0 1 0"/>
    </joint>

    <link name="middle_left_wheel">
        <visual>
			<origin xyz="0 0 0" rpy="${PI / 2} 0 0" />
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
            </geometry>
            <material name="Red" />
        </visual>
        <collision>
			<origin xyz="0 0 0" rpy="${PI / 2} 0 0" />
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_width}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="middle_left_wheel">
        <mu1 value="${lateral_friction}" />
        <mu2 value="${spinning_friction}" />
        <kp value="${contact_stiffness}" />
        <kd value="${contact_damping}" />
        <fdir1 value="1 0 0"/>
        <minDepth>0</minDepth>
        <material>Gazebo/Red</material>
    </gazebo>

    <joint name="middle_left_marker_joint" type="fixed">
        <parent link="middle_left_wheel" />
        <child link="middle_left_marker" />
        <origin xyz="0.015 0.0175 0" rpy="0 0 0" />
    </joint>

    <link name="middle_left_marker">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.03 0.005 0.005" />
            </geometry>
            <material name="White" />
        </visual>
        <inertial>
            <mass value="${marker_mass}" />
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
        </inertial>
    </link>
    <gazebo reference="middle_left_marker">
        <material>Gazebo/White</material>
    </gazebo>

    <!-- ********************** RIGHT ********************************* -->
    <joint name="middle_right_wheel_joint" type="continuous">
        <parent link="body_link" />
        <child link="middle_right_wheel" />
		<origin xyz="0 ${-1 * (wheel_separation/2 + wheel_width/2)} 0" rpy="0 0 0" />
        <axis xyz="0 1 0"/>
    </joint>

    <link name="middle_right_wheel">
        <visual>
			<origin xyz="0 0 0" rpy="${PI / 2} 0 0" />
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
            </geometry>
            <material name="Red" />
        </visual>
        <collision>
			<origin xyz="0 0 0" rpy="${PI / 2} 0 0" />
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_width}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="middle_right_wheel">
        <mu1 value="${lateral_friction}" />
        <mu2 value="${spinning_friction}" />
        <kp value="${contact_stiffness}" />
        <kd value="${contact_damping}" />
        <fdir1 value="1 0 0"/>
        <minDepth>0</minDepth>
        <material>Gazebo/Red</material>
    </gazebo>

    <joint name="middle_right_marker_joint" type="fixed">
        <parent link="middle_right_wheel" />
        <child link="middle_right_marker" />
        <origin xyz="0.015 -0.0175 0" rpy="0 0 0" />
    </joint>

    <link name="middle_right_marker">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.03 0.005 0.005" />
            </geometry>
            <material name="White" />
        </visual>
        <inertial>
            <mass value="${marker_mass}" />
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
        </inertial>
    </link>
    <gazebo reference="middle_right_marker">
        <material>Gazebo/White</material>
    </gazebo>
    
    
    <!-- ********************** WHEEL LINKS FRONT *********************************  -->
    <!-- ********************** LEFT ********************************* -->
    <joint name="front_left_wheel_joint" type="continuous">
        <parent link="body_link" />
        <child link="front_left_wheel" />
		<origin xyz="0.104 ${wheel_separation/2 + wheel_width/2} 0" rpy="0 0 0" />
        <axis xyz="0 1 0"/>
    </joint>

    <link name="front_left_wheel">
        <visual>
			<origin xyz="0 0 0" rpy="${PI / 2} 0 0" />
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
            </geometry>
            <material name="Red" />
        </visual>
        <collision>
			<origin xyz="0 0 0" rpy="${PI / 2} 0 0" />
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_width}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="front_left_wheel">
        <mu1 value="${lateral_friction}" />
        <mu2 value="${spinning_friction}" />
        <kp value="${contact_stiffness}" />
        <kd value="${contact_damping}" />
        <fdir1 value="1 0 0"/>
        <minDepth>0</minDepth>
        <material>Gazebo/Red</material>
    </gazebo>

    <joint name="front_left_marker_joint" type="fixed">
        <parent link="front_left_wheel" />
        <child link="front_left_marker" />
        <origin xyz="0.015 0.0175 0" rpy="0 0 0" />
    </joint>

    <link name="front_left_marker">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.03 0.005 0.005" />
            </geometry>
            <material name="White" />
        </visual>
        <inertial>
            <mass value="${marker_mass}" />
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
        </inertial>
    </link>
    <gazebo reference="front_left_marker">
        <material>Gazebo/White</material>
    </gazebo>

    <!-- ********************** RIGHT ********************************* -->
    <joint name="front_right_wheel_joint" type="continuous">
        <parent link="body_link" />
        <child link="front_right_wheel" />
		<origin xyz="0.104 ${-1 * (wheel_separation/2 + wheel_width/2)} 0" rpy="0 0 0" />
        <axis xyz="0 1 0"/>
    </joint>

    <link name="front_right_wheel">
        <visual>
			<origin xyz="0 0 0" rpy="${PI / 2} 0 0" />
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
            </geometry>
            <material name="Red" />
        </visual>
        <collision>
			<origin xyz="0 0 0" rpy="${PI / 2} 0 0" />
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_width}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="front_right_wheel">
        <mu1 value="${lateral_friction}" />
        <mu2 value="${spinning_friction}" />
        <kp value="${contact_stiffness}" />
        <kd value="${contact_damping}" />
        <fdir1 value="1 0 0"/>
        <minDepth>0</minDepth>
        <material>Gazebo/Red</material>
    </gazebo>

    <joint name="front_right_marker_joint" type="fixed">
        <parent link="front_right_wheel" />
        <child link="front_right_marker" />
        <origin xyz="0.015 -0.0175 0" rpy="0 0 0" />
    </joint>

    <link name="front_right_marker">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.03 0.005 0.005" />
            </geometry>
            <material name="White" />
        </visual>
        <inertial>
            <mass value="${marker_mass}" />
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
        </inertial>
    </link>
    <gazebo reference="front_right_marker">
        <material>Gazebo/White</material>
    </gazebo>

</robot>