joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0
    sticky_buttons: false

teleop_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.7
    scale_linear_turbo:
      x: 1.2

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 0.5
    scale_angular_turbo:
      yaw: 1.0

    publish_stamped_twist: false

    enable_button: 6
    enable_turbo_button: 7
    require_enable_button: true
    
    publish_stamped_twist: true
    frame: teleop_twist_joy